spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/renting_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  mvc:
    format:
      date: dd/MM/yyyy